import React, { useEffect, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { useDispatch, useSelector } from "react-redux";
import { fetchProductById, fetchRecommendations } from "../redux/thunks/productThunks.js";
import { clearSelectedProduct } from "../redux/slices/productSlice.js";
import { addToCart } from "../redux/slices/cartSlice.js";
import ProductCard from "../components/ProductCard.jsx";
import { FiStar, FiShoppingBag, FiArrowLeft } from "react-icons/fi";

const ProductDetail = () => {
  const { id } = useParams();
  const dispatch = useDispatch();
  const navigate = useNavigate();

  const { selectedProduct: product, recommendations, loading } = useSelector((state) => state.products);
  const [qty, setQty] = useState(1);
  const [toast, setToast] = useState(false);

  useEffect(() => {
    if (id) {
      dispatch(fetchProductById(id));
      dispatch(fetchRecommendations(id));
    }
    return () => dispatch(clearSelectedProduct());
  }, [dispatch, id]);

  const handleAdd = () => {
    dispatch(
      addToCart({
        productId: product._id,
        name: product.name,
        price: product.price,
        image: product.image,
        stock: product.stock,
        quantity: qty,
      })
    );
    setToast(true);
    setTimeout(() => setToast(false), 2000);
  };

  if (loading || !product) {
    return <div className="min-h-[50vh] flex items-center justify-center font-medium">Loading details...</div>;
  }

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 py-8 space-y-12">
      <button onClick={() => navigate(-1)} className="inline-flex items-center gap-2 text-sm text-ink/60 hover:text-ink font-semibold">
        <FiArrowLeft /> Back to catalog
      </button>

      <div className="bg-white border border-ink/10 rounded-3xl p-6 md:p-10 shadow-sm grid md:grid-cols-2 gap-10">
        <div className="aspect-square bg-sand rounded-2xl overflow-hidden">
          <img src={product.image} alt={product.name} className="w-full h-full object-cover" />
        </div>

        <div className="flex flex-col justify-between space-y-6">
          <div>
            <span className="text-xs uppercase tracking-widest text-clay font-bold bg-sand px-3 py-1 rounded-full mb-3 inline-block">
              {product.category}
            </span>
            <h1 className="text-3xl md:text-4xl font-extrabold mb-3">{product.name}</h1>
            <div className="flex items-center gap-2 mb-4">
              <span className="bg-amber-100 text-amber-800 px-2 py-0.5 rounded text-xs font-bold flex items-center gap-1">
                <FiStar className="fill-amber-500 text-amber-500" /> {product.ratings}
              </span>
              <span className="text-xs text-ink/50">({product.numReviews} ratings)</span>
            </div>
            <p className="text-ink/75 leading-relaxed text-sm mb-6">{product.description}</p>
            <div className="border-t border-b border-ink/10 py-4">
              <p className="text-3xl font-extrabold">₹{product.price}</p>
              <p className={`text-xs mt-1 font-semibold ${product.stock > 0 ? "text-moss" : "text-red-500"}`}>
                {product.stock > 0 ? `${product.stock} units in inventory` : "Out of stock"}
              </p>
            </div>
          </div>

          <div className="flex items-center gap-4">
            <div className="flex items-center border border-ink/20 rounded-full bg-sand/30">
              <button onClick={() => setQty(Math.max(1, qty - 1))} className="w-10 h-10 font-bold">−</button>
              <span className="w-8 text-center text-sm font-semibold">{qty}</span>
              <button onClick={() => setQty(Math.min(product.stock, qty + 1))} className="w-10 h-10 font-bold">+</button>
            </div>
            <button
              onClick={handleAdd}
              disabled={product.stock === 0}
              className="flex-1 bg-ink text-white rounded-full py-3.5 px-6 flex items-center justify-center gap-2 hover:bg-plum font-semibold disabled:opacity-40"
            >
              <FiShoppingBag /> {toast ? "Added to Cart!" : "Add to Cart"}
            </button>
          </div>
        </div>
      </div>

      {recommendations.length > 0 && (
        <section className="pt-6">
          <h2 className="text-2xl font-bold mb-1">Recommended for You</h2>
          <p className="text-xs text-ink/50 mb-6">Generated by RapidMiner Similarity Matrix Model</p>
          <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-4">
            {recommendations.map((item) => (
              <ProductCard key={item._id} product={item} />
            ))}
          </div>
        </section>
      )}
    </div>
  );
};

export default ProductDetail;