import mongoose from "mongoose";
import dotenv from "dotenv";
import Product from "./models/product.js";
import connectDB from "./config/dbConnection.js";

dotenv.config();

const products = [
  // ==================== ELECTRONICS ====================
  {
    name: "Mechanical Gaming Keyboard",
    description: "Compact 75% hot-swappable RGB keyboard with tactile brown switches.",
    price: 3499,
    category: "Electronics",
    brand: "KeyPulse",
    stock: 18,
    ratings: 4.7,
    numReviews: 31,
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "ANC Wireless Over-Ear Headphones",
    description: "Hybrid active noise cancelling headphones with 40-hour battery life and quick charge.",
    price: 6999,
    category: "Electronics",
    brand: "AuraSound",
    stock: 25,
    ratings: 4.6,
    numReviews: 48,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Ultra-Lightweight Gaming Mouse",
    description: "64g wireless optical mouse featuring 26K DPI sensor and ultra-flexible paracord cable.",
    price: 2199,
    category: "Electronics",
    brand: "SwiftGrip",
    stock: 40,
    ratings: 4.5,
    numReviews: 29,
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "27-Inch 165Hz IPS Gaming Monitor",
    description: "QHD 2560x1440 frameless panel with 1ms response time and HDR400 support.",
    price: 21499,
    category: "Electronics",
    brand: "PixelCraft",
    stock: 12,
    ratings: 4.8,
    numReviews: 64,
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "True Wireless Stereo Earbuds",
    description: "In-ear buds with dynamic 11mm drivers, low-latency gaming mode, and IPX5 resistance.",
    price: 1899,
    category: "Electronics",
    brand: "SonicWave",
    stock: 55,
    ratings: 4.3,
    numReviews: 87,
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Magnetic 3-in-1 Wireless Charging Stand",
    description: "Fast-charging folding dock compatible with phone, smartwatch, and earbuds.",
    price: 2499,
    category: "Electronics",
    brand: "VoltSync",
    stock: 30,
    ratings: 4.4,
    numReviews: 22,
    image: "https://images.unsplash.com/photo-1622445262464-84b1456045b6?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "4K Streaming Action Camera",
    description: "Dual-screen 4K/60FPS waterproof action camera with electronic image stabilization.",
    price: 8499,
    category: "Electronics",
    brand: "PeakMotion",
    stock: 15,
    ratings: 4.2,
    numReviews: 19,
    image: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "1080p Pro Stream Webcam",
    description: "Full HD 60FPS autofocus streaming webcam with privacy shutter and stereo mics.",
    price: 3299,
    category: "Electronics",
    brand: "StreamOptics",
    stock: 35,
    ratings: 4.6,
    numReviews: 53,
    image: "https://images.unsplash.com/photo-1585060544812-6b45742d762f?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Portable Bluetooth Speaker (20W)",
    description: "Rugged outdoor cylindrical speaker with 360-degree sound and IP67 dust/waterproofing.",
    price: 2799,
    category: "Electronics",
    brand: "BassCore",
    stock: 42,
    ratings: 4.7,
    numReviews: 76,
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Aluminum 7-in-1 USB-C Hub",
    description: "Supports 4K HDMI, 100W Power Delivery, SD/TF card readers, and USB 3.0 ports.",
    price: 1599,
    category: "Electronics",
    brand: "NexConnect",
    stock: 50,
    ratings: 4.5,
    numReviews: 38,
    image: "https://images.unsplash.com/photo-1625842268584-8f3296236761?w=600&auto=format&fit=crop&q=80",
  },

  // ==================== WEARABLES & FITNESS ====================
  {
    name: "AMOLED Smart Fitness Watch",
    description: "1.43-inch vivid AMOLED display with continuous heart rate, SpO2, and GPS tracking.",
    price: 4999,
    category: "Wearables",
    brand: "FitVibe",
    stock: 22,
    ratings: 4.6,
    numReviews: 61,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Adjustable Cast Iron Dumbbells (20kg)",
    description: "Quick-adjust selector dial dumbbell set with non-slip knurled grip handles.",
    price: 7499,
    category: "Fitness",
    brand: "IronPeak",
    stock: 14,
    ratings: 4.8,
    numReviews: 43,
    image: "https://images.unsplash.com/photo-1638803040283-7a5ffd48dad5?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Non-Slip Eco-Friendly Yoga Mat",
    description: "6mm high-density natural rubber exercise mat with alignment guideline grid.",
    price: 1499,
    category: "Fitness",
    brand: "ZenFlow",
    stock: 60,
    ratings: 4.7,
    numReviews: 89,
    image: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Loop Resistance Bands (Set of 5)",
    description: "100% natural latex booty and workout exercise bands with different resistance tiers.",
    price: 699,
    category: "Fitness",
    brand: "FlexTone",
    stock: 80,
    ratings: 4.4,
    numReviews: 95,
    image: "https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Deep Tissue Percussion Massage Gun",
    description: "Handheld muscle massager with 6 speed levels and 4 interchangeable massage heads.",
    price: 3499,
    category: "Fitness",
    brand: "ReliefPro",
    stock: 19,
    ratings: 4.5,
    numReviews: 36,
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "High-Speed Ball Bearing Jump Rope",
    description: "Tangle-free steel cable speed jump rope designed for cardio and crossfit training.",
    price: 499,
    category: "Fitness",
    brand: "SpeedTrack",
    stock: 75,
    ratings: 4.3,
    numReviews: 40,
    image: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "High-Density Foam Roller",
    description: "18-inch molded foam roller for muscle recovery, physical therapy, and deep massage.",
    price: 899,
    category: "Fitness",
    brand: "FlexTone",
    stock: 33,
    ratings: 4.6,
    numReviews: 27,
    image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Insulated Stainless Steel Shaker Bottle",
    description: "750ml leak-proof protein shaker with silent whisk ball and double-wall vacuum insulation.",
    price: 999,
    category: "Fitness",
    brand: "HydroMix",
    stock: 45,
    ratings: 4.7,
    numReviews: 58,
    image: "https://images.unsplash.com/photo-1577705998148-6da4f3963bc8?w=600&auto=format&fit=crop&q=80",
  },

  // ==================== APPAREL & FOOTWEAR ====================
  {
    name: "Heavyweight Boxy Fit Cotton T-Shirt",
    description: "240 GSM 100% combed cotton streetwear t-shirt with reinforced ribbed collar.",
    price: 899,
    category: "Fashion",
    brand: "UrbanThread",
    stock: 65,
    ratings: 4.5,
    numReviews: 42,
    image: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Oversized Fleece Pullover Hoodie",
    description: "Warm brushed-fleece cotton hoodie with a double-layered hood and front pouch pocket.",
    price: 1899,
    category: "Fashion",
    brand: "UrbanThread",
    stock: 28,
    ratings: 4.8,
    numReviews: 50,
    image: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Slim Tapered Stretch Denim Jeans",
    description: "Classic 5-pocket blue denim jeans engineered with comfort stretch elastane.",
    price: 2199,
    category: "Fashion",
    brand: "DenimCraft",
    stock: 35,
    ratings: 4.4,
    numReviews: 33,
    image: "https://images.unsplash.com/photo-1542272604-780c96856592?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Breathable Road Running Shoes",
    description: "Lightweight knit upper runners featuring cushioned EVA midsole and grippy rubber sole.",
    price: 3299,
    category: "Fashion",
    brand: "AeroStrider",
    stock: 20,
    ratings: 4.6,
    numReviews: 71,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Classic White Leather Court Sneakers",
    description: "Minimalist low-top sneakers constructed with genuine leather and padded insoles.",
    price: 2799,
    category: "Fashion",
    brand: "StrideClassic",
    stock: 26,
    ratings: 4.7,
    numReviews: 39,
    image: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Tailored Linen Casual Button-Down Shirt",
    description: "Breathable 100% pure linen regular-fit long-sleeve casual summer shirt.",
    price: 1699,
    category: "Fashion",
    brand: "Vanguard",
    stock: 32,
    ratings: 4.3,
    numReviews: 24,
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Quick-Dry Active Running Shorts",
    description: "7-inch moisture-wicking shorts with built-in compression liner and zipped phone pocket.",
    price: 999,
    category: "Fashion",
    brand: "AeroStrider",
    stock: 48,
    ratings: 4.5,
    numReviews: 45,
    image: "https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Thermal Windbreaker Jacket",
    description: "Lightweight water-resistant outer layer with adjustable hood and reflective trims.",
    price: 2999,
    category: "Fashion",
    brand: "PeakMotion",
    stock: 16,
    ratings: 4.6,
    numReviews: 18,
    image: "https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=600&auto=format&fit=crop&q=80",
  },

  // ==================== BAGS & ACCESSORIES ====================
  {
    name: "Water-Resistant Commuter Backpack",
    description: "Minimalist rolltop laptop backpack with padded 16-inch compartment and USB port.",
    price: 2499,
    category: "Accessories",
    brand: "PackForm",
    stock: 22,
    ratings: 4.7,
    numReviews: 67,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Full Grain Leather Trifold Wallet",
    description: "Handcrafted slim wallet equipped with RFID security protection and ID window.",
    price: 1199,
    category: "Accessories",
    brand: "Hide & Stitch",
    stock: 44,
    ratings: 4.5,
    numReviews: 35,
    image: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Polarized Classic Aviator Sunglasses",
    description: "UV400 scratch-resistant metal frame sunglasses with anti-glare tinted lenses.",
    price: 1599,
    category: "Accessories",
    brand: "SolarShade",
    stock: 38,
    ratings: 4.6,
    numReviews: 52,
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Vegetable Tanned Leather Belt",
    description: "1.5-inch solid thick leather strap fitted with a brushed antique brass buckle.",
    price: 1299,
    category: "Accessories",
    brand: "Hide & Stitch",
    stock: 29,
    ratings: 4.4,
    numReviews: 21,
    image: "https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Minimalist Quartz Dress Watch",
    description: "Ultra-thin stainless steel casing with genuine leather strap and sapphire crystal.",
    price: 4499,
    category: "Accessories",
    brand: "Chronos",
    stock: 17,
    ratings: 4.8,
    numReviews: 40,
    image: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Corduroy Crossbody Sling Bag",
    description: "Versatile everyday shoulder bag with multiple zippered organizer compartments.",
    price: 899,
    category: "Accessories",
    brand: "PackForm",
    stock: 45,
    ratings: 4.3,
    numReviews: 17,
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&auto=format&fit=crop&q=80",
  },

  // ==================== HOME, KITCHEN & LIVING ====================
  {
    name: "Gooseneck Electric Pour-Over Kettle",
    description: "Precision temperature control kettle (0.8L) with keep-warm mode and LED panel.",
    price: 3799,
    category: "Home & Kitchen",
    brand: "BrewCraft",
    stock: 14,
    ratings: 4.9,
    numReviews: 73,
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Stainless Steel French Press (1L)",
    description: "Double-walled vacuum insulated coffee maker with 4-level filtration screen.",
    price: 1799,
    category: "Home & Kitchen",
    brand: "BrewCraft",
    stock: 28,
    ratings: 4.7,
    numReviews: 66,
    image: "https://images.unsplash.com/photo-1517668808822-9ebb02ae2a0e?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Pre-Seasoned Cast Iron Skillet (10-Inch)",
    description: "Even-heating heavy-duty cast iron pan suited for induction, stove, grill, or oven.",
    price: 1599,
    category: "Home & Kitchen",
    brand: "ForgeCook",
    stock: 30,
    ratings: 4.8,
    numReviews: 82,
    image: "https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Japanese High-Carbon Chef Knife (8-inch)",
    description: "Razor-sharp VG-10 steel core blade with ergonomic pakkawood handle.",
    price: 2899,
    category: "Home & Kitchen",
    brand: "ForgeCook",
    stock: 18,
    ratings: 4.8,
    numReviews: 39,
    image: "https://images.unsplash.com/photo-1593618998160-e34014e67546?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Organic Bamboo End-Grain Cutting Board",
    description: "Extra thick wood block with juice drip grooves and side recessed handles.",
    price: 1199,
    category: "Home & Kitchen",
    brand: "NatureHome",
    stock: 35,
    ratings: 4.6,
    numReviews: 28,
    image: "https://images.unsplash.com/photo-1594385208974-2e75f8d7bb48?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Digital Touchscreen Air Fryer (4.5L)",
    description: "360-degree rapid air circulation fryer with 8 preset one-touch cooking modes.",
    price: 5299,
    category: "Home & Kitchen",
    brand: "CuisinePro",
    stock: 16,
    ratings: 4.6,
    numReviews: 54,
    image: "https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Aromatherapy Ultrasonic Essential Oil Diffuser",
    description: "500ml wood grain mist humidifier with 7 ambient LED colors and auto shut-off.",
    price: 1499,
    category: "Home & Kitchen",
    brand: "AuraLiving",
    stock: 40,
    ratings: 4.5,
    numReviews: 60,
    image: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Hand-Poured Soy Wax Scented Candle",
    description: "Clean-burning crackling wood-wick candle infused with amber, cedar, and vanilla notes.",
    price: 699,
    category: "Home & Kitchen",
    brand: "AuraLiving",
    stock: 50,
    ratings: 4.7,
    numReviews: 44,
    image: "https://images.unsplash.com/photo-1603006905003-be475563bc59?w=600&auto=format&fit=crop&q=80",
  },

  // ==================== WORKSPACE & STATIONERY ====================
  {
    name: "Ergonomic Memory Foam Lumbar Cushion",
    description: "Orthopedic contoured backrest cushion for desk chairs with breathable mesh cover.",
    price: 1299,
    category: "Workspace",
    brand: "ErgoRest",
    stock: 27,
    ratings: 4.4,
    numReviews: 37,
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Dimmable LED Computer Monitor Light Bar",
    description: "Eye-care screen hanging lamp with auto-dimming and 3 color temperature settings.",
    price: 2199,
    category: "Workspace",
    brand: "BeamDesk",
    stock: 23,
    ratings: 4.7,
    numReviews: 49,
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Waterproof Vegan Leather Desk Mat (90x40cm)",
    description: "Dual-sided extended mouse pad and desk protector for home office setups.",
    price: 799,
    category: "Workspace",
    brand: "DeskMate",
    stock: 55,
    ratings: 4.6,
    numReviews: 63,
    image: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Anodized Aluminum Laptop Riser",
    description: "Sturdy ergonomic laptop stand for notebooks up to 17 inches with heat-vent cutouts.",
    price: 1399,
    category: "Workspace",
    brand: "ErgoRest",
    stock: 34,
    ratings: 4.7,
    numReviews: 41,
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Hardcover Dotted Journal (A5)",
    description: "160 GSM bleed-proof bamboo paper notebook featuring ribbon markers and inner pocket.",
    price: 649,
    category: "Workspace",
    brand: "NoteCraft",
    stock: 70,
    ratings: 4.8,
    numReviews: 30,
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Refillable Matte Metal Rollerball Pen",
    description: "Balanced weighted aluminum writing instrument loaded with smooth 0.5mm black gel ink.",
    price: 499,
    category: "Workspace",
    brand: "NoteCraft",
    stock: 85,
    ratings: 4.5,
    numReviews: 26,
    image: "https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=600&auto=format&fit=crop&q=80",
  },

  // ==================== PERSONAL CARE ====================
  {
    name: "Sonic Whitening Electric Toothbrush",
    description: "40,000 VPM vibration motor with 5 cleaning modes and wireless inductive charging.",
    price: 1999,
    category: "Personal Care",
    brand: "PureSmile",
    stock: 28,
    ratings: 4.6,
    numReviews: 57,
    image: "https://images.unsplash.com/photo-1559591937-e106069036c8?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Cold-Pressed Organic Moroccan Argan Oil",
    description: "100% pure moisturizing nourishing treatment oil for dry hair, beard, and skin.",
    price: 899,
    category: "Personal Care",
    brand: "DermaPure",
    stock: 52,
    ratings: 4.7,
    numReviews: 68,
    image: "https://images.unsplash.com/photo-1608248597359-25f02bc265e1?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "Double-Edge Safety Razor with 20 Blades",
    description: "Traditional chrome-plated brass wet shaving razor designed for zero irritation.",
    price: 999,
    category: "Personal Care",
    brand: "BarberCraft",
    stock: 36,
    ratings: 4.8,
    numReviews: 46,
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80",
  },
  {
    name: "SPF 50+ Invisible Matte Sunscreen Gel",
    description: "Broad-spectrum non-comedogenic sunscreen leaves zero white cast and no greasy residue.",
    price: 599,
    category: "Personal Care",
    brand: "DermaPure",
    stock: 65,
    ratings: 4.5,
    numReviews: 81,
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80",
  },
];

// Seeding function
const seedProducts = async () => {
  try {
    await connectDB();
    await Product.deleteMany();
    await Product.insertMany(products);
    console.log(`Successfully seeded ${products.length} products!`);
    process.exit(0);
  } catch (error) {
    console.error("Error while seeding data:", error);
    process.exit(1);
  }
};

seedProducts();